app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import InicioTemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('core.bitacora.urls')),
    path('', InicioTemplateView.as_view(), name='inicio'),
    path('login/', include('core.login.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/login/urls.py
from django.urls import path, include
from core.login.views import LoginFormView, LogoutFormView, RegistroCreateFormView

app_name = 'login'

urlpatterns = [
    path('',LoginFormView.as_view(), name="login"),
    path('logout/',LogoutFormView.as_view(), name="logout"),
    path('registro/',RegistroCreateFormView.as_view(), name="Registro")
]

app/core/login/models.py
from django.db import models

# Create your models here.

app/core/login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import *
from django.forms import EmailField

from core.bitacora.models import *


class RegistroUsuario(UserCreationForm):
    class Meta:
        model = user
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'avatar',
            'numero_documento',

        ]
        labels = {
            'username': "nombre de usuario",
            'first_name': 'ingrese  nombre',
            'last_name': 'Ingrese Apellido',
            'email': 'Ingrese email',
            'avatar': ' imagen',
            'numero_documento': 'Ingrese numero de documento'

        }

app/core/login/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView
from django.http import Http404

from core.bitacora.models import user
from core.login.forms import RegistroUsuario


class LoginFormView(LoginView):
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        # si se quiere ir a el inicio de sesion cuando una misma ya este iniciada
        # se realiza una validacion si la sesion esta iniciada entonces redireccionar a listar personas
        if request.user.is_authenticated:
            return redirect("app:Dashboard")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'SRF CONSULTORES'
        context ['url'] = 'Incio de session'
        return context

class LogoutFormView(LogoutView):
    next_page = '/login/'


class RegistroCreateFormView(CreateView):
    model = user
    template_name = "registro.html"
    form_class = RegistroUsuario
    success_url = reverse_lazy('inicio')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # def post(self, request, *args, **kwargs):
    #     data= {}
    #     try:
    #         print(request.POST)
    #         print(request.FILES)
    #
    #     except:
    #         pass

app/core/login/templates/login.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="{% static "img/logo.png" %}" rel="icon" class="img-circle">

    <title>{{ url }}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <img class="img-circle card-img-top img-fluid img-size-50" src="{% static 'img/logo.png' %}">
        <a href="{% url 'inicio' %}">{{ titulo }}</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Sign in to start your session</p>

            <form action="." method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    {{ form.username|add_class:"form-control"|attr:"placeholder: Usuario" }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    {{ form.password|add_class:"form-control"|attr:"placeholder: Contraseña" }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">

                    <!-- /.col -->
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-block">Iniciar Sesion</button>
                    </div>
                    <br>
                    <br>
                    <div class="col-12">
                        <a type="button" href="{% url 'login:Registro' %}" class="btn btn-secondary btn-block">Registro</a>
                    </div>
                    <!-- /.col -->
                </div>
            </form>


            <!-- /.social-auth-links -->


        </div>
        <!-- /.login-card-body -->
    </div>

    <script type="application/javascript">
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}
    </script>
</div>
<!-- jQuery -->
<script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
</body>
</html>

app/core/login/templates/registro.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <link href="{% static "img/logo.png" %}" rel="icon" class="img-circle">

    <title>Registro de usuario</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
    <div class="register-logo">
        <img class="img-circle card-img-top img-fluid img-size-50" src="{% static 'img/logo.png' %}"> <a
            href="{{ home }}"><b>SRF</b>
        CONSULTORES</a>
    </div>

    <div class="card">
        <div class="card-body register-card-body">
            <p class="login-box-msg">Registro de Nuevo usuario</p>

            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                <div class="input-group mb-3">
                    {{ form.first_name|add_class:"form-control"|attr:"placeholder: Nombre"|attr:"type:text" }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    {{ form.last_name|add_class:"form-control"|attr:"placeholder: Apellido"|attr:"type:text" }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    {{ form.username|add_class:"form-control"|attr:"placeholder: Nombre usuario"|attr:"type:text" }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    {{ form.email|add_class:"form-control"|attr:"placeholder: Ingrese su correo"|attr:"type:email" }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-at"></span>
                        </div>
                    </div>
                </div>

                <div class="input-group mb-3">
                    {{ form.numero_documento|add_class:"form-control"|attr:"placeholder: Ingrese numero de documento"|attr:"type:text" }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-sort-numeric-up"></span>
                        </div>
                    </div>
                </div>

                <div class="input-group mb-3">
                    {{ form.password1|add_class:"form-control"|attr:"placeholder: Ingrese su contraseña"|attr:"type:password" }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-key"></span>
                        </div>
                    </div>
                </div>

                <div class="input-group mb-3">
                    {{ form.password2|add_class:"form-control"|attr:"placeholder: Confirme su contraseña"|attr:"type:password" }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-key"></span>
                        </div>
                    </div>
                </div>

                <div class="input-group mb-4">
                    <span>Ingrese avatar</span>
                    {{ form.avatar|add_class:"form-control-sm"|attr:"type:file" }}
                    <div class="input-group-append">

                    </div>
                </div>

                <hr>


                <div class="col-12">
                    <button type="submit" class="btn btn-primary btn-block">Registar Usurario</button>
                </div>
                <br>
                <br>
                <div class="row">
                    <div class="col-6">
                        <button type="reset" class="btn btn-secondary btn-block">Cancelar
                        </button>
                    </div>
                    <div class="col-6">
                        <a href="{% url 'login:login' %}" class="btn btn-danger btn-block">Volver
                        </a>
                    </div>
                    <!-- /.col -->
                </div>
            </form>


        </div>
        <!-- /.form-box -->
    </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>

<script type="application/javascript">
    {% if form.errors %}
        var errors = '';
        {% for field in form %}
            {% for error in field.errors %}
                errors += '{{ error }}\n';
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            errors += '{{ error }}\n';
        {% endfor %}
        Swal.fire({
            title: 'Error!',
            text: errors,
            icon: 'error'
        });
    {% endif %}
</script>
</body>
</html>