app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import InicioTemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('core.bitacora.urls')),
    path('', InicioTemplateView.as_view(), name='inicio'),
    path('login/', include('core.login.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/bitacora/urls.py
from django.urls import path

from core.bitacora.views.bitacora.views import BitacoraCreatedView, BitacoraListView, BitacoraUpdateView, \
    BitacoraDetallePdfView, BitacoraDeleteView
from core.bitacora.views.dashboard.views import DashboardView
from core.bitacora.views.personas.views import *

app_name = 'app'

urlpatterns = [
    path('listapersonas/', personasListView.as_view(), name='lista_personas'),
    path('nuevapersona/', PersonaCreateView.as_view(), name='Nueva_Persona'),
    # se envian parametros por ulr  en los casos de eliminar y actualizar se envia
    # la llave primaria
    path('editPersona/<int:pk>/', PersonaUpdate.as_view(), name='Editar_Persona'),
    path('deletePersona/<int:pk>/', PersonaDeleteView.as_view(), name='Eliminar_Persona'),
    # Dashboard
    path('', DashboardView.as_view(), name='Dashboard'),
    # Bitacora
    path('bitacoraadd/', BitacoraCreatedView.as_view(), name='bitacora'),
    path('bitacoralista/', BitacoraListView.as_view(), name='ListarBitacora'),
    path('bitacoraedit/<int:pk>/', BitacoraUpdateView.as_view(), name='EditarBitacora'),
    path('bitacorapdf/<int:pk>/', BitacoraDetallePdfView.as_view(), name='ImpresionDetalle'),
    path('bitacoradelete/<int:pk>/', BitacoraDeleteView.as_view(), name='EliminarBitacora'),

]

app/core/login/urls.py
from django.urls import path, include
from core.login.views import LoginFormView, LogoutFormView, RegistroCreateFormView

app_name = 'login'

urlpatterns = [
    path('',LoginFormView.as_view(), name="login"),
    path('logout/',LogoutFormView.as_view(), name="logout"),
    path('registro/',RegistroCreateFormView.as_view(), name="Registro")
]

app/templates/simple/body.html
{% extends 'home.html' %}

{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'simple/header.html' %}
        <!-- Sidebar -->
        {% include 'simple/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"><small>{{ titulo }}</small></h1>
                        </div>

                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{ home }}">Home</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    </body>
{% endblock %}

app/templates/simple/header.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'inicio' %}" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"> </i> {{ request.user.get_full_name }}
            </a>

            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">
                       Ultimo Acceso: {{ hora }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login:logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

app/templates/simple/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="#" class="brand-link">
        <img src="{% static 'img/logo.png' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">SRF CONSULTORES</span>

    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_avatar }}" class="brand-image img-circle elevation-3" alt="User Image"
                     style="">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.get_full_name }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimientos</li>
                <li class="nav-item">
                    <a href="{% url 'app:lista_personas' %}" class="nav-link">
                        <i class="nav-icon fas fa-user-astronaut"></i>
                        <p>
                            Personas
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'app:ListarBitacora' %}" class="nav-link">
                        <i class="nav-icon fas fa-clipboard-list"></i>
                        <p>
                            Bitacoras
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-diagnoses "></i>
                        <p>
                            Admin
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>