app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import InicioTemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('core.bitacora.urls')),
    path('', InicioTemplateView.as_view(), name='inicio'),
    path('login/', include('core.login.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/bitacora/urls.py
from django.urls import path

from core.bitacora.views.bitacora.views import BitacoraCreatedView, BitacoraListView, BitacoraUpdateView, \
    BitacoraDetallePdfView, BitacoraDeleteView
from core.bitacora.views.dashboard.views import DashboardView
from core.bitacora.views.personas.views import *

app_name = 'app'

urlpatterns = [
    path('listapersonas/', personasListView.as_view(), name='lista_personas'),
    path('nuevapersona/', PersonaCreateView.as_view(), name='Nueva_Persona'),
    # se envian parametros por ulr  en los casos de eliminar y actualizar se envia
    # la llave primaria
    path('editPersona/<int:pk>/', PersonaUpdate.as_view(), name='Editar_Persona'),
    path('deletePersona/<int:pk>/', PersonaDeleteView.as_view(), name='Eliminar_Persona'),
    # Dashboard
    path('', DashboardView.as_view(), name='Dashboard'),
    # Bitacora
    path('bitacoraadd/', BitacoraCreatedView.as_view(), name='bitacora'),
    path('bitacoralista/', BitacoraListView.as_view(), name='ListarBitacora'),
    path('bitacoraedit/<int:pk>/', BitacoraUpdateView.as_view(), name='EditarBitacora'),
    path('bitacorapdf/<int:pk>/', BitacoraDetallePdfView.as_view(), name='ImpresionDetalle'),
    path('bitacoradelete/<int:pk>/', BitacoraDeleteView.as_view(), name='EliminarBitacora'),

]

app/core/bitacora/forms.py
from django.forms import *
from core.bitacora.models import *


class NuevaPersona(ModelForm):
    class Meta:
        model = Personas
        field = '__all__'
        exclude = ['id']
        widgets = {
            'nombre': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control',
                    'rows': 3,
                    'cols': 3
                }

            ),
            'apellido': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control ',
                    'rows': 3,
                    'cols': 3
                }
            ),
            'tipo_documento': Select(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control select2',
                    'rows': 3,
                    'cols': 3
                }
            ),
            'cedula': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control ',
                    'rows': 3,
                    'cols': 3
                }
            ),
            'correo': EmailInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control ',
                    'rows': 3,
                    'cols': 3
                }
            ),
            'telefono': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control ',
                    'rows': 3,
                    'cols': 3
                }
            ),

        }

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data


class EditPersona(ModelForm):
    class Meta:
        model = Personas
        field = '__all__'
        exclude = ['id']
        widgets = {
            'nombre': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control',
                    'rows': 3,
                    'cols': 3
                }

            ),
            'apellido': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control ',
                    'rows': 3,
                    'cols': 3
                }
            ),
            'tipo_documento': Select(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control select2',
                    'rows': 3,
                    'cols': 3
                }
            ),
            'cedula': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control ',
                    'rows': 3,
                    'cols': 3
                }
            ),
            'correo': EmailInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control ',
                    'rows': 3,
                    'cols': 3
                }
            ),
            'telefono': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre',
                    'class': 'form-control ',
                    'rows': 3,
                    'cols': 3
                }
            ),

        }


class BitacoraForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Bitacoras
        field = '__all__'
        exclude = ['id', 'estado']
        widgets = {
            'reunion': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre de la reunion',
                    'class': 'form-control ',
                    'rows': 3,
                    'cols': 3
                }

            ),
            'numero_personas': TextInput(
                attrs={
                    'placeholder': 'Numero de asistentes',
                    'class': 'form-control',
                    'rows': 3,
                    'cols': 3
                }
            ),
            'lugar_encuentro': Select(
                attrs={
                    'class': 'form-control select2',
                    'style': 'width: 100%'

                }
            ),
            'observaciones': Textarea(
                attrs={
                    'placeholder': 'Escriba las observaciones',
                    'class': 'form-control',
                    'rows': 3,
                    'cols': 3

                }
            ),
            'usuario': Select(
                attrs={
                    'class': 'form-control select2',
                    'style': 'width: 100%'
                }

            ),
            'fecha': DateInput(attrs={
                'type': 'date',
                'class': 'form-control'
            })

        }

app/core/bitacora/views/bitacora/views.py
import json

# Libreria de PFDS
import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders

from datetime import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import JsonResponse, HttpResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, UpdateView, View, DeleteView

from core.bitacora.forms import BitacoraForm
from core.bitacora.models import Bitacoras, Personas, DetalleBitacora, user


class BitacoraListView(LoginRequiredMixin, ListView):
    model = Bitacoras
    template_name = 'bitacora/ListadoBitacora.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # Se envia la variable data dentro de un diccionario
        data = {}
        try:
            action = request.POST['action']
            if action == 'buscarDatos':
                data = []
                for i in Bitacoras.objects.all():
                    data.append(i.cambioJson())
            elif action == 'buscarDetalle':
                data = []
                for i in DetalleBitacora.objects.filter(bitacora_id=request.POST['id']):
                    data.append(i.cambioJson())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Listado de bitacoras'
        context['home'] = reverse_lazy('app:Dashboard')
        context['create_url'] = reverse_lazy('app:bitacora')
        context['status_url'] = reverse_lazy('app:ListarBitacora')
        context['status'] = 'lista de personas'
        context['bienvenido'] = 'Bienvenido'
        context['hora'] = datetime.now().ctime()
        context['datos'] = user.objects.all().order_by('id')
        return context


class BitacoraCreatedView(LoginRequiredMixin, CreateView):
    model = Bitacoras
    form_class = BitacoraForm
    template_name = 'bitacora/crearbitacora.html'
    success_url = reverse_lazy('app:Dashboard')
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # Data es la variable que vamos a llevar al front para
        # interactuar con Ajax
        data = {}
        # Try ejecuta la accion y genera excepciones ante los errores
        try:
            # La variable Action evalua si lleva un atributo action el template
            # entonces se ejecuta la siguiente accion
            action = request.POST['action']
            # Si en el templeate action tiene el valor de Search_persons entonces guarda la data en un listado
            if action == 'search_persons':
                data = []
                # Se crea la variable clientes para enviar la tabla personas al templeate filtrado por nombre
                personas = Personas.objects.filter(nombre__icontains=request.POST['busqueda'])[0:5]
                # se recorre la variable para obtener todos los datos
                for i in personas:
                    # se envian los datos sen formato Json
                    item = i.cambioJson()
                    item['value'] = i.nombre
                    data.append(item)
            elif action == 'add':
                vents = json.loads(request.POST['vents'])
                bitacora = Bitacoras()
                bitacora.usuario_id = vents['usuario']
                bitacora.reunion = vents['reunion']
                bitacora.numero_personas = vents['numero_personas']
                bitacora.fecha = vents['fecha']
                bitacora.lugar_encuentro_id = vents['lugar_encuentro']
                bitacora.observaciones = vents['observaciones']
                bitacora.save()
                for i in vents['personas']:
                    detalle = DetalleBitacora()
                    detalle.bitacora_id = bitacora.id
                    detalle.persona_id = i['id']
                    detalle.tapabocas = bool(i['tapabocas'])
                    detalle.distancia = bool(i['distancia'])
                    detalle.observaciones = i['observacionesper']
                    detalle.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)

        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Nuevo Registro'
        context['home'] = reverse_lazy('app:Dashboard')
        context['status_url'] = reverse_lazy('')
        context['status'] = 'Crear registro'
        context['bienvenido'] = 'Crear Registro'
        context['detalle'] = []
        context['action'] = 'add'
        return context


class BitacoraUpdateView(LoginRequiredMixin, UpdateView):
    model = Bitacoras
    form_class = BitacoraForm
    template_name = 'bitacora/crearbitacora.html'
    success_url = reverse_lazy('app:ListarBitacora')
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # Data es la variable que vamos a llevar al front para
        # interactuar con Ajax
        data = {}
        # Try ejecuta la accion y genera excepciones ante los errores
        try:
            # La variable Action evalua si lleva un atributo action el template
            # entonces se ejecuta la siguiente accion
            action = request.POST['action']
            # Si en el templeate action tiene el valor de Search_persons entonces guarda la data en un listado
            if action == 'search_persons':
                data = []
                # Se crea la variable clientes para enviar la tabla personas al templeate filtrado por nombre
                personas = Personas.objects.filter(nombre__icontains=request.POST['busqueda'])[0:5]
                # se recorre la variable para obtener todos los datos
                for i in personas:
                    # se envian los datos sen formato Json
                    item = i.cambioJson()
                    item['value'] = i.nombre
                    data.append(item)
            elif action == 'edit':
                with transaction.atomic():
                    vents = json.loads(request.POST['vents'])
                    bitacora = self.get_object()
                    bitacora.usuario_id = vents['usuario']
                    bitacora.reunion = vents['reunion']
                    bitacora.numero_personas = vents['numero_personas']
                    bitacora.fecha = vents['fecha']
                    bitacora.lugar_encuentro_id = vents['lugar_encuentro']
                    bitacora.observaciones = vents['observaciones']
                    bitacora.save()
                    bitacora.detallebitacora_set.all().delete()
                for i in vents['personas']:
                    detalle = DetalleBitacora()
                    detalle.bitacora_id = bitacora.id
                    detalle.persona_id = i['id']
                    detalle.tapabocas = bool(i['tapabocas'])
                    detalle.distancia = bool(i['distancia'])
                    detalle.observaciones = i['observacionesper']
                    detalle.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_detalle_bitacora(self):
        data = []
        try:
            for i in DetalleBitacora.objects.filter(bitacora_id=self.get_object().id):
                item = i.persona.cambioJson()
                item['tapabocas'] = i.tapabocas
                item['distancia'] = i.distancia
                item['observaciones'] = i.observaciones
                data.append(item)
        except:
            pass
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Edicion Registro'
        context['home'] = reverse_lazy('app:Dashboard')
        context['status_url'] = reverse_lazy('')
        context['status'] = 'Crear registro'
        context['bienvenido'] = 'Crear Registro'
        context['tablapersonas'] = Personas.objects.all()
        context['action'] = 'edit'
        context['detalle'] = json.dumps(self.get_detalle_bitacora())
        return context


class BitacoraDeleteView(LoginRequiredMixin, DeleteView):
    model = Bitacoras
    template_name = 'bitacora/EliminarBitacora.html'
    success_url = reverse_lazy('app:ListarBitacora')
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Eliminacion Bitacora'
        context['home'] = reverse_lazy('app:ListarBitacora')
        context['status_url'] = reverse_lazy('app:EliminarBitacora')
        context['status'] = 'Eliminar registro'
        context['bienvenido'] = 'Eliminar registro'
        context['hora'] = datetime.now().ctime()
        return context

    def post(self, request, *args, **kwargs):

app/core/bitacora/views/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView


class DashboardView(TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['titulo'] = 'Panel de Administrador'
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request,*args,**kwargs)

app/core/bitacora/templates/personas/crear.html
{% extends 'simple/body.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action="{% url 'app:Nueva_Persona' %}">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ titulo }}
                </h3>
            </div>
            <div class="card-body ">
                {% csrf_token %}
                <!-- El nombre de la variable que paso por medio de la vista es action
                el valor es el que se le asigna en la vista -->
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="email" >{{ field.label }}:</label>
                        {{ field|add_class:'col-xs-3'|attr:'autocomplete:off' }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success btn-flat" id="enviar">
                    <i class="fas fa-check"></i> Guardar Registro
                </button>
            </div>
        </div>
    </form>
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}
        $(function () {
            $('.select2').select2({
                theme: "bootstrap4",
                language: 'es'
            });
            $('form').on('submit', function (e) {
                e.preventDefault()
                //se crea una variable para ingresar los datos en un arreglo
                //this hace referencia al fomulario y sis datos
                //serializeArray guarda los datos en un arreglo
                var parametros = new FormData(this);

                submit_ajax(window.location.pathname, parametros, 'Notificacion', '¿Desea agregar esta persona?', function () {
                    location.href = '{{ home }}';
                });


            });
        });


    </script>
{% endblock %}

app/core/bitacora/templates/personas/delete.html
{% extends 'simple/body.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ titulo }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <h5> Atencion!</h5>
                        Error en elemento diligenciado
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-ban"></i> Antes de eliminar</h5>
                    ¿Quiere eliminar el registro de la persona {{ object.nombre }} {{ object.apellido }}?
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success btn-flat">
                    <i class="fas fa-check"></i> Eliminar Registro
                </button>
                <a href="{% url 'app:lista_personas' %} " class="btn btn-secondary btn-flat">
                    <i class="fa fa-times"> </i> Conservar Registro</a>
            </div>
        </div>
    </form>

{% endblock %}
{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('form').on('submit', function (e) {
                e.preventDefault()

                var parametros = new FormData();
                submit_ajax(window.location.pathname, parametros, 'Alerta', 'Confirme la eliminacion', function () {
                    location.href = '{{ home }}';
                });
            });
        });

    </script>
{% endblock %}

app/core/bitacora/templates/personas/edit.html
{% extends 'simple/body.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ titulo }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {% if form.errors %}

                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Atencion!</h5>
                        Error en elemento diligenciado
                    </div>

                {% endif %}

                {{ form }}

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success btn-flat">
                    <i class="fas fa-check"></i> Guardar Registro
                </button>
            </div>
        </div>
    </form>
    <script>
        {% if form.errors %}
            Swal.fire({
                icon: 'error',
                title: '',
                text: 'Ingrese correctamente los campos',
            })
        {% endif %}



    </script>
{% endblock %}

app/core/bitacora/templates/personas/lista.html
{% extends 'listado.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'js/ListadoPersonas.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

{% endblock %}
{% block columns %}


    {% if object_list %}


        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Tipo Documento</th>
            <th scope="col">Cedula</th>
            <th scope="col">Correo</th>
            <th scope="col">Telefono</th>
            <th scope="col">Opcion</th>
        </tr>
    {% else %}

    {% endif %}

{% endblock %}
{% block rows %}


{% endblock %}